### ISSUE TITLE
Support for infinite recursion

### ISSUE THREAD

**Issue by abhishek-compro** [bhch/django-jsonform#101]
Sample schema which works on https://bhch.github.io/react-json-form/playground/#8-recursion but doesn't work when using `django-jsonform`:

```json
{
  "$defs": {
    "and": {
      "type": "object",
      "keys": {
        "and": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/$defs/and",
                "title": "and"
              },
              {
                "$ref": "#/$defs/or",
                "title": "or"
              }
            ]
          }
        }
      }
    },
    "or": {
      "type": "object",
      "keys": {
        "or": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/$defs/and",
                "title": "and"
              },
              {
                "$ref": "#/$defs/or",
                "title": "or"
              }
            ]
          }
        }
      }
    }
  },
  "oneOf": [
    {
      "$ref": "#/$defs/or",
      "title": "or"
    }
  ]
}
```

**Comment by bhch** [comment]
Which version are you on? Check using:

```sh
$ python -c "import django_jsonform; print(django_jsonform.__version__)
```

**Comment by abhishek-compro** [comment]
> Which version are you on?

2.17.0

**Comment by bhch** [comment]
So I did some tests. Seems to work as expected.

Here's an animated GIF:

![animated gif](https://user-images.githubusercontent.com/6051897/236684833-ea83a726-9220-4810-88d1-2f65c0587536.gif)

---

What issues are you getting?

**Comment by abhishek-compro** [comment]
I was getting the following error:

```
TypeError: t is undefined
    Re http://localhost:8000/static/django_jsonform/react-json-form.js:1
    g http://localhost:8000/static/django_jsonform/react-json-form.js:1
    _e http://localhost:8000/static/django_jsonform/react-json-form.js:1
    render http://localhost:8000/static/django_jsonform/react-json-form.js:1
    React 13
    render http://localhost:8000/static/django_jsonform/react-json-form.js:1
    initJSONForm http://localhost:8000/static/django_jsonform/index.js:62
    initializeAllForNode http://localhost:8000/static/django_jsonform/index.js:100
    init http://localhost:8000/static/django_jsonform/index.js:105
    <anonymous> http://localhost:8000/static/django_jsonform/index.js:145
    EventListener.handleEvent* http://localhost:8000/static/django_jsonform/index.js:144
    <anonymous> http://localhost:8000/static/django_jsonform/index.js:149
react-dom.production.min.js:141:274
```

What should I do?

**Comment by bhch** [comment]
Try disabling your browser cache.

If this is a production environment, you must also run the `collectstatic` command to replace old static files with new ones.

**Comment by abhishek-compro** [comment]
Got this in chrome:

```
react-dom.production.min.js:141 TypeError: Cannot read properties of undefined (reading 'length')
    at Re (react-json-form.js:1:52698)
    at g (react-json-form.js:1:56760)
    at _e (react-json-form.js:1:57098)
    at a.render (react-json-form.js:1:59517)
    at Te (react-dom.production.min.js:119:308)
    at Ch (react-dom.production.min.js:119:105)
    at Pj (react-dom.production.min.js:233:139)
    at di (react-dom.production.min.js:168:305)
    at Nj (react-dom.production.min.js:168:236)
    at sc (react-dom.production.min.js:168:96)
```

> Try disabling your browser cache.

I did clear the cache. How do I disable it though?

Its development environment.

To be more precise I am using the following model:

```python
class UserFilter(models.Model):
    filters = JSONField(
        schema={
            "$defs": {
                "and": {
                    "type": "object",
                    "properties": {
                        "and": {
                            "type": "array",
                            "items": {
                                "oneOf": [
                                    {"$ref": "#/$defs/and", "title": "and"},
                                    {"$ref": "#/$defs/or", "title": "or"},
                                ]
                            },
                        }
                    },
                },
                "or": {
                    "type": "object",
                    "properties": {
                        "or": {
                            "type": "array",
                            "items": {
                                "oneOf": [
                                    {"$ref": "#/$defs/and", "title": "and"},
                                    {"$ref": "#/$defs/or", "title": "or"},
                                ]
                            },
                        }
                    },
                },
            },
            "oneOf": [
                {"$ref": "#/$defs/and", "title": "and"},
                {"$ref": "#/$defs/or", "title": "or"},
            ],
        },
        default=dict,
    )
    name = models.CharField(max_length=512, unique=True)
```

**Comment by bhch** [comment]
`default=dict` is what's causing the problem.

The widget is receiving `{}` as the default data which doesn't match any subschemas listed under `oneOf`.

To fix it, you should:

 - either stop providing a default value because the widget will automatically create appropriate empty data.
 - or if you must, then the default value must match at least one of the subschemas, e.g.: `default={"and": []}`.

---

Anyway, I'll mark this issue as a bug because the widget should handle this type of cases more gracefully and should produce helpful error messages.

**Comment by abhishek-compro** [comment]
That worked. Thanks!!

**Comment by bhch** [comment]
@sgocg Hi, I just tested the scenario you mentioned. It's working completely fine for me. I tested with the latest version (2.21.0).

Which version are you using?

**Comment by sgocg** [comment]
Thanks for testing it out. And apologies that the previous schema wasn't fully representative. I tried pasting a (much too) simplified version of the schema as my original schema is quite large.

In any case, I was able to simplify it differently now. Here's the original schema:

```json
{
  "type": "object",
  "properties": {
    "data": {
      "type": "object",
      "title": "Example",
      "oneOf": [
        {
          "title": "Table",
          "properties": {
            "type": {
              "type": "string",
              "default": "table",
              "widget": "hidden"
            },
            "columns": {
              "title": "Columns",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "title": "Header"
                  },
                  "type": {
                    "type": "string",
                    "title": "Type",
                    "choices": [
                      "string",
                      "number",
                      "integer",
                      "boolean"
                    ],
                    "default": "string",
                    "required": true
                  },
                  "default": {
                    "type": "array",
                    "title": "Prepopulate rows (EN)",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

If I update the schema to this:

```json
{
  "type": "object",
  "properties": {
    "data": {
      "type": "object",
      "title": "Example",
      "oneOf": [
        {
          "title": "Table",
          "properties": {
            "type": {
              "type": "string",
              "default": "table",
              "widget": "hidden"
            },
            "columns": {
              "title": "Columns",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "title": "Header"
                  },
                  "type": {
                    "type": "string",
                    "title": "Type",
                    "choices": [
                      "string",
                      "number",
                      "integer",
                      "boolean"
                    ],
                    "default": "string",
                    "required": true
                  },
                  "default": {
                    "type": "array",
                    "title": "Prepopulate rows (EN)",
                    "items": {
                      "type": "string"
                    }
                  },
                  "default_de": {
                    "type": "array",
                    "title": "Prepopulate rows (DE)",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

... i.e. add the `default_de` property, the admin widget doesn't render with the following message:
<img width="570" alt="Screenshot 2023-11-28 at 10 02 20 AM" src="https://github.com/bhch/django-jsonform/assets/141132507/db6f21b9-f41f-4923-aee5-bca0304f8d11">

In the database I'm using the following value:

```json
{
  "data": {
    "type": "table",
    "columns": [
      {
        "type": "string",
        "title": "Column 1",
        "default": [
          "first",
          "second",
          "third"
        ]
      },
      {
        "type": "number",
        "title": "Column 2",
        "default": []
      },
      {
        "type": "string",
        "title": "Column 3",
        "default": []
      }
    ]
  }
}
```

I was using 2.17.0 earlier but upgraded to 2.21.0 but the problem still persists.

**Comment by bhch** [comment]
@sgocg I am able to reproduce the error now. It's a separate issue altogether. Will be tracked in #131.
